INSERT INTO prospecta_directorio (empresa,nombre,email,ciudad,estado) VALUES
('Lao & Asociados','Lao Largaespada Jorge Edwin','largaespada_jorge@gmail.com',39,15),
('Despacho Lara Eduarte S.c.','Lara Eduarte Jose Antonio','eduarte_jose@gmail.com',39,15),
('Unimer S.a.','Jimenez Luna Ana Lia','luna_ana@gmail.com',39,15),
('Consultoria Interdic Desarrollo Cid','Denton Lister Charles Frederick','lister_charles@gmail.com',39,15),
('Interamericana De Desarrollo S.a.','Ramirez Hernandez Fernando','ramirez_hernandez@gmail.com',39,15),
('Razo Fernandez Ernesto','','razo_fernandez@gmail.com',39,15),
('Asesores Aduanales Y Comerciales','Arce Portuguez Rodolfo','arce_portuguez@gmail.com',39,15),
('Kpmg Sociedad Anonima','Amen Chen Alfonso','amen_chen@gmail.com',39,15),
('Price Waterhouse Y Compañia S.c','Gomez Carranza Maria Vanessa','carranza_maria@gmail.com',39,15),
('Alvaro Cedeño Y Asociados','Cedeño Gomez Alvaro','cedeno_gomez@gmail.com',39,15),
('Victor Borge Y Asociados','Borge Gonzalez Victor Guillermo','gonzalez_victor@gmail.com',39,15),
('Comercio Y Desarr.tinoco Y Pacheco','Gomez Zuñiga Vidal','gomez_zuniga@gmail.com',39,15),
('Mentiras Piadosas, S.A.','Checo Ramirez Carlos Luis','ramirez_carlos@gmail.com',39,15),
('Setecoop R.l.','Oconitrillo Fonseca Danilo','oconitrillo_fonseca@gmail.com',39,15),
('Ee Mora Consultores S.a.','Mora Valverde Eduardo Ernesto','valverde_eduardo@gmail.com',39,15),
('Grupo Camacho S.a.','Camacho Cordoba Carlos Humberto','cordoba_carlos@gmail.com',39,15),
('Dimerca S.a.','Chinchilla Salazar Rafael Emilio','salazar_rafael@gmail.com',39,15),
('B & S Consultores S.a.','Blanco Montero Bernardo','blanco_montero@gmail.com',39,15),
('Iniciativas De Desar.empresarial Sa','Seas Molina Flor Nazaria','molina_flor@gmail.com',39,15),
('Grupo Dando Cr S.a.','Gomar Laguardia Carlos Eduardo','laguardia_carlos@gmail.com',39,15),
('Deloitte & Touche S.a','Rodriguez Araya Luis Guillermo','araya_luis@gmail.com',39,15),
('Bermudez Mendez & Asociados','Bermudez Hidalgo Omar Jesus','hidalgo_omar@gmail.com',39,15),
('Centro Latino De Capacitacion Y Con','Coto Fernandez Gonzalo Gerardo','fernandez_gonzalo@gmail.com',39,15),
('Techadores Unios','Gonzalez Romero Martin','gonzalez_romero@gmail.com',39,15),
('Fundacion Ucr Para La Invest Fundev','Guillen Pacheco Roberto Francisco','pacheco_roberto@gmail.com',39,15),
('Gretrog S.a.','Vargas Rodriguez Roger','vargas_rodriguez@gmail.com',39,15),
('Correduria De Seguros Metropolitanos S.a.','Melendez Jimenez Luis Paulino','jimenez_luis@gmail.com',39,15),
('Mez Ajoy Edgar Luis','','ajoy_edgar@gmail.com',39,15),
('Fundacion Servicio Civil Fuscidere','Flores Rojas Fabio','flores_rojas@gmail.com',39,15),
('Empanadas Para Atletas','Laya Lucke Julio Antonio','lucke_julio@gmail.com',39,15),
('Puentes Nasales','Rodriguez Bolaños Edgar','rodriguez_bolanos@gmail.com',39,15),
('Fusiles Comicos','Mario Panroido','poza_mario@gmail.com',39,15),
('Guevara Y Asociados Consultores Ec','Seas Molina Flor Nazaria','molina_flor@gmail.com',39,15),
('Evara','Cordero Maria Del Milagro','maria_del@gmail.com',39,15),
('Demoscopia Sa','Zamora Lopez Guillermo Alonso','lopez_guillermo@gmail.com',39,15),
('Fundepos','Chacon Montero Jose Angel','montero_jose@gmail.com',39,15),
('Ingenieria De Capitales Indecap S.a.','Morua Nuñez Victor','morua_nunez@gmail.com',39,15),
('Perspectivas De Desarrollo','Zuñiga Umaña Fernando','zuniga_umana@gmail.com',39,15),
('Grupo Analisis Y Consultoria Ac S.a.','Rojas Campbell Rosa Maria','campbell_rosa@gmail.com',39,15),
('Aimec Consultores S.a','Flores Cubero Olga Marta','cubero_olga@gmail.com',39,15),
('Gutierrez Marin Y Asociados','Gutierrez Herrera Mario Alberto','herrera_mario@gmail.com',39,15),
('Mgi Hernandez Y Asociados Contadores','Hernandez Hernandez Juan Augusto','hernandez_juan@gmail.com',39,15),
('Ascodi Sa','Guzman Guzman Luis Alberto','guzman_luis@gmail.com',39,15),
('Ja Haslam Sa','Ambram Foldvari Jorge Roberto','foldvari_jorge@gmail.com',39,15),
('Marina Laplace','Mora Mata Manuel Emilio','mata_manuel@gmail.com',39,15),
('Price Waterhouse Coopers Consultore','Scott Quiros Ana Victoria','quiros_ana@gmail.com',39,15),
('Fudeci','Kelso Baldioceda Percival','kelso_baldioceda@gmail.com',39,15),
('Macetones Yucatecos','Coronado Coronado Harold','coronado_coronado@gmail.com',39,15),
('Lasos De Novia','Bonilla Boza Sergio','bonilla_boza@gmail.com',39,15),
('Materia Prima Para Kinder','Muñoz Cespedes Carlos Hernan','cespedes_carlos@gmail.com',39,15),
('Creacion De Capitales S.a.','Gonzalez Camacho Carlos Alberto','camacho_carlos@gmail.com',39,15),
('Universidad Metropolitana Castro Carazo','Villalta Gewurtz Gonzalo','villalta_gewurtz@gmail.com',39,15),
('Espeleologos Unidos','Castro Harrigan Alvaro','castro_harrigan@gmail.com',39,15),
('Centro De Estudios Economicos Y Ambientales','Adamson Badilla Marcos E.','badilla_marcos@gmail.com',39,15),
('Sociedad Calificad Riesgo Centroame','Piedra Cerdas Ana Cecilia','cerdas_ana@gmail.com',39,15),
('Lanzas Industriales','Barquero Arce Gary Rafael','arce_gary@gmail.com',39,15),
('It Informacion Total S.a.','Guzman Madrigal Freddy Alberto','madrigal_freddy@gmail.com',39,15),
('Consul Empres Rojas Robles Asoc S.a','Rodriguez Mico Eli Arturo','mico_eli@gmail.com',39,15),
('Sabanas Finas','Mojas Sanchez Gerardo','mojas_sanchez@gmail.com',39,15),
('Servicios Integrales De Ases Cosmos','Coto Perez Carmen','coto_perez@gmail.com',39,15),
('Respuestas Del Mercadeo Inter. S.a.','Araya Alpizar Carlo Magno','alpizar_carlo@gmail.com',39,15),
('Ecoanalisis S.a','Monge Gonzalez Ricardo','monge_gonzalez@gmail.com',39,15),
('Van Der Leer S.a.','Gallardo Castro Laura','gallardo_castro@gmail.com',39,15),
('Tortas Coloquiales','Peñoz Cespedes Carlos Hernan','cespedes_carlos@gmail.com',39,15),
('Inmobiliaria Finantek Del Oeste S.a.','Carboni Aguiluz Silvia','carboni_aguiluz@gmail.com',39,15),
('Grupo Libertad Promotores De Capacitacion Empresarial S.a','Ortega Ortega Angel Abelino','ortega_angel@gmail.com',39,15),
('Doris Peters Y Asociados S.a.','Chaverri Vargas Jose Maria','vargas_jose@gmail.com',39,15),
('Consejeros Economicos Y Financ Sa','Naranjo Villalobos Fernando Enrique','villalobos_fernando@gmail.com',39,15),
('Desarrollos Informaticos Deinsa','Lopez Vallejos Jose Luis','vallejos_jose@gmail.com',39,15),
('Enfoque Estudios De Opinion Sw S.a.','Vilchez Sanchez Jose Guillermo','sanchez_jose@gmail.com',39,15),
('Excelencia Tecnica En Informaticas','Murillo Navarro Ana Maria','navarro_ana@gmail.com',39,15),
('Cegesti','Murillo Diaz Lidieth','murillo_diaz@gmail.com',39,15),
('Asociacion Costarricense De Gestore','Olivas Rojas Carlos Francisco','rojas_carlos@gmail.com',39,15),
('Despacho Carvajal Y Colegiados Cpa Sa','Montero Martinez Gerardo Miguel','martinez_gerardo@gmail.com',39,15),
('Alta Direccion Sa','Duarte Lopez Jose Herbert','lopez_jose@gmail.com',39,15),
('Abbq Consultores','Hernandez Mena Ada','hernandez_mena@gmail.com',39,15),
('Iz','Barquero Raul Esteban','barquero_raul@gmail.com',39,15),
('Agencia De Aduanas Multimodal S.a.','Zamora Ureña Maria De Los Angeles','de_los@gmail.com',39,15),
('Lmo Consultores Multidisciplinarios','Mora Mata Manuel Emilio','mata_manuel@gmail.com',39,15),
('Asociacion La Academia De Centroam','Lizano Fait Eduardo','lizano_fait@gmail.com',39,15),
('Imerca S.a.','Espinoza Rodriguez Ileana','espinoza_rodriguez@gmail.com',39,15),
('Buzo Y Asociados S.a.','Buzo Orozco Mario Alberto','orozco_mario@gmail.com',39,15),
('Manpower Costa Rica S.a.','Ordeñana Vargas Digna Alejandra','vargas_digna@gmail.com',39,15),
('Universidad Fundepos Alma Mater S.a.','Morales Zamora Marco Antonio','zamora_marco@gmail.com',39,15),
('Perritos Para Paseos Largos','Rita Bonilla Luis Enrique','bonilla_luis@gmail.com',39,15),
('Cotera & Asociados','Fonseca Hornedo Alfredo Francisco','hornedo_alfredo@gmail.com',39,15),
('Alta Gestion Consultores Sa','Montoya Delgado Verny','montoya_delgado@gmail.com',39,15),
('Hay Group Srl','Brenes Ramirez Andrea Maria','ramirez_andrea@gmail.com',39,15),
('Fitch Costa Rica Calificadora Riesg','Lewis Hernandez Allan','lewis_hernandez@gmail.com',39,15),
('Cidi Sa','Torres Calvo Jose Agustin','calvo_jose@gmail.com',39,15),
('Proveedor Integral De Precios','Rodriguez Del Paso Eduardo','del_paso@gmail.com',39,15),
('Instituto De Altos Estudios En Gerencia Social','Iae Guzman Saborio Gilberto','guzman_saborio@gmail.com',39,15),
('Fundacion Ciudadania Activa','Guzman Saborio Gilberto','guzman_saborio@gmail.com',39,15),
('Finanzas Corporativas De Centroamer','Venegas Renauld Roberto','venegas_renauld@gmail.com',39,15),
('Asesorias Creativas Desarrollo Integral Acdi S.a.','Fernandez Alvarez Carlos Eduardo','alvarez_carlos@gmail.com',39,15),
('Finance Consulting Group','Brenes Piedra Felipe Alberto','piedra_felipe@gmail.com',39,15),
('Gente De Talento Sociedad Anonima','Sirker Polanco Nancy Emilia','polanco_nancy@gmail.com',39,15),
('Tatum Global Consulting Centro America S.a.','Lopez Alezard Linda Consuelo','alezard_linda@gmail.com',39,15),
('Ernst & Young S.a.','Artavia Arce Giovanni','artavia_arce@gmail.com',39,15),
('Lusof Bz Consultores S.a','Zuñiga Guerrero Silvia Lorena','guerrero_silvia@gmail.com',39,15),
('Asesoria Profesional Interdiciplinaria Api S.a.','Masis Vargas Francisco Jose','vargas_francisco@gmail.com',39,15),
('Soluciones Administrativas Y Financieras S.a.','Solano Zuñiga Marco Antonio','zuniga_marco@gmail.com',39,15),
('Consulsasso & Asociados S.a.','Sasso Centeno Rima Maria','centeno_rima@gmail.com',39,15),
('Brenes Artavia Consultores Y Asociados S.a.','Brenes Castro Esteban Roberto','castro_esteban@gmail.com',39,15),
('Asociacion Camara De Indusrias Costa Rica','Castillo Diaz Marta Eugenia','diaz_marta@gmail.com',39,15),
('Asociacion Universidad Para La Cooperacion Internacional','Marin Vargas Franklin Gerardo','vargas_franklin@gmail.com',39,15),
('Opciones Tecnicas Para El Desarrollo S.a','Quesada Zuñiga Juan Manuel','zuniga_juan@gmail.com',39,15),
('Sulz Marketing Consultores','Sulzbacher Luiz Gustavo','sulzbacher_luiz@gmail.com',39,15),
('F&f Reasearch And Development S.a','Acuña Reyes Helmut','acuna_reyes@gmail.com',39,15),
('Centro De Desarrollo Solera S.a','Solera Umaña Carlos Alberto','umana_carlos@gmail.com',39,15),
('Aesco S.a.','Meneses Martinez Denis','meneses_martinez@gmail.com',39,15),
('Asesora En Alta Tecnologia','Rosales Tijerino Julio Tomas','tijerino_julio@gmail.com',39,15),
('Novaster Ge Sa','Montero Rodriguez Danilo','montero_rodriguez@gmail.com',39,15),
('Corporacion De Asesores En Comercio Exterior','Vargas Leiva Federico','vargas_leiva@gmail.com',39,15),
('Bussiness Model Innovation Consulting S.a','Jimenez Barquero Leonid Ivan','barquero_leonid@gmail.com',39,15),
('Conideas Sociedad Anonima','Seas Oses Luis Diego','oses_luis@gmail.com',39,15),
('Nahaorqui Consultores S.a.','Quiros Robles Natalia','quiros_robles@gmail.com',39,15),
('Tiz','Ramirez Hazel','poza_ramirez@gmail.com',39,15),
('Consulting Focus Management','Quiros Villarreal Jose Maria','villarreal_jose@gmail.com',39,15),
('Profit Strategy Group - Psg','Hernandez Carvajal Gabriel','hernandez_carvajal@gmail.com',39,15),
('Gestion Y Venta De Bienes Gyv S.a','Soto Morera Marcelo','soto_morera@gmail.com',39,15),
('Leadership Technologies Costa Rica Sa','Peraza Gutierrez Otto','peraza_gutierrez@gmail.com',39,15),
('Insight Consulting De Costa Rica S.a','Montero Cordero Paola','montero_cordero@gmail.com',39,15),
('Transparencia Bursatil S.a','Rodriguez Del Paso Eduardo','del_paso@gmail.com',39,15),
('Valmer Costa Rica S.a','Acon Chan Yin Mei','chan_yin@gmail.com',39,15),
('Legal Solutions Group S.a','Castro Vargas Randal Bernardo','vargas_randal@gmail.com',39,15),
('Asociacion Centroamericana Para La Economia','Lobo Ugalde Susy Victoria','ugalde_susy@gmail.com',39,15),
('Vh Finanzas Limitada','Hip Ureña Ernesto Yuichau','urena_ernesto@gmail.com',39,15),
('Estudio De Informacion Economica Esieco S.a','Gutierrez Gutierrez Francisco De Paula','francisco_de@gmail.com',39,15),
('Coronado Y Perez As Consultores S.a','Chacon Conejo Bernardo','chacon_conejo@gmail.com',39,15),
('Impacto Organizacional S.a','Masis Calvo Alejandro','masis_calvo@gmail.com',39,15),
('Fortis Servicios Empresariales S.a','Poutvinski Anton','poza_poutvinski@gmail.com',39,15),
('Aldi Zeledon & Asociados','Calderon Lobo Luis Paulino','lobo_luis@gmail.com',39,15),
('Jav Estudios Para El Desarrollo S.a','Borge Gonzalez Victor Guillermo','gonzalez_victor@gmail.com',39,15),
('Consultores Profesionales Al Servicio Del Talento Srl','Chacon Conejo Bernardo','chacon_conejo@gmail.com',39,15),
('Ajsxxi S.a','Rojas Gomez Eduardo','rojas_gomez@gmail.com',39,15),
('Latin Vector S.a','Saad Meza Roberto','saad_meza@gmail.com',39,15),
('Valor Inmueble.com S.a','Brumley Obando Yorlene','brumley_obando@gmail.com',39,15),
('Academia Internacional De Seminarios Svc S.a','Muñoz Perez Lourdes Adriana','perez_lourdes@gmail.com',39,15),
('El Camino Asesores S.a','Molina Navarro German','molina_navarro@gmail.com',39,15),
('Coopenae Sociedad Agencia De Seguros S.a','Centeno Madrigal Bernal Eladio','madrigal_bernal@gmail.com',39,15),
('Turnaround Group S.a','Segura Calderon Andres De Jesus','feoslosdos@hotmail.com',120,15);